### ISSUE TITLE
TypeError: this.prerender is not a function

### ISSUE THREAD

**Issue by emdahlstrom** [miaolz123/vue-markdown#60]
Hi!
Trying to use the preprender prop to filter the contents but I get the error below. Any idea?

`{ TypeError: this.prerender is not a function
    at Proxy.render (/vuenuxt/node_modules/vue-markdown/dist/vue-markdown.common.js:321:52)
    at VueComponent.Vue._render (/vuenuxt/node_modules/vue/dist/vue.runtime.common.js:4472:22)
    at renderComponentInner (/vuenuxt/node_modules/vue-server-renderer/build.js:7356:25)
    at renderComponent (/vuenuxt/node_modules/vue-server-renderer/build.js:7326:5)
    at RenderContext.renderNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7242:5)
    at RenderContext.next (/vuenuxt/node_modules/vue-server-renderer/build.js:2382:14)
    at cachedWrite (/vuenuxt/node_modules/vue-server-renderer/build.js:2242:9)
    at renderStringNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7422:5)

    at RenderContext.renderNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7240:5)
    at RenderContext.next (/vuenuxt/node_modules/vue-server-renderer/build.js:2382:14)
    at cachedWrite (/vuenuxt/node_modules/vue-server-renderer/build.js:2242:9)
    at renderStringNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7431:5)
    at RenderContext.renderNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7240:5)
    at RenderContext.next (/vuenuxt/node_modules/vue-server-renderer/build.js:2382:14)
    at cachedWrite (/vuenuxt/node_modules/vue-server-renderer/build.js:2242:9)
    at renderStringNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7431:5)
    at RenderContext.renderNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7240:5)
    at RenderContext.next (/vuenuxt/node_modules/vue-server-renderer/build.js:2382:14)
    at cachedWrite (/vuenuxt/node_modules/vue-server-renderer/build.js:2242:9)
    at renderStringNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7431:5)
    at RenderContext.renderNode (/vuenuxt/node_modules/vue-server-renderer/build.js:7240:5)
    at RenderContext.next (/vuenuxt/node_modules/vue-server-renderer/build.js:2382:14) statusCode: 500,
 name: 'TypeError' }`

The pug
`vue-markdown(prerender='replaceTokens()') {{ document.description }}`

**Comment by tyankatsu0105** [comment]
You should return parameter in prerender function like this:

```vue
<template>
  <VueMarkdown :prerender="prerender" />
</template>

<script>
import VueMarkdown from "vue-markdown";

export default {
  components: {
    VueMarkdown,
  },
  methods: {
    prerender (str) {
    return str
  },
};
</script>
```
